name: deploy to shinteka
on:
  push:
    branches: [test-self-hostet-runner]
jobs:
  test:
    runs-on: self-hosted
    name: test
    steps:
      - name: Test Code
        run: docker container stop S3S
        run: docker container trusting_sammet S3S
